### ISSUE TITLE
Innkeeper's Daughter

### ISSUE THREAD

**Issue by GoldFishie** [MilleXIV/SX_Databar#1]
Legion turned [The Innkeeper's Daughter](http://www.wowhead.com/item=64488/the-innkeepers-daughter) into a toy, leaving the addon unable to detect whether or not the player has it and leaving the hearthstone button grayed out as a result.

**Comment by MilleXIV** [comment]
Should be good to go. I don't actually have this toy so I can't comment on whether or not it works, so please update me.

**Comment by GoldFishie** [comment]
It's fixed, thanks!
